version: 2
jobs:
  build:
    docker:
      - image: quay.io/pik-software/base-django:3.7

    working_directory: ~/repo

    steps:
      - checkout

      - restore_cache:
          name: Restore Python dependencies
          keys:
            - v1-dependencies-{{ .Branch }}-{{ checksum "requirements.dev.txt" }}

      - run:
          name: Install Python dependencies
          command: |
            python -m venv .venv
            . .venv/bin/activate
            pip install -r requirements.dev.txt

      - save_cache:
          name: Cache Python dependencies
          key: v1-dependencies-{{ .Branch }}-{{ checksum "requirements.dev.txt" }}
          paths:
            - ./.venv

      - run:
          name: PIP Check
          command: |
            . .venv/bin/activate
            pip check

      - run:
          name: Checksum Prospector
          command: |
            . .venv/bin/activate
            if [[ "${CIRCLE_BRANCH}" != "master" && "${CIRCLE_BRANCH}" != "stage" ]]; then
              find -type f -iname '*.py' ! -path '*tests*' ! -path '*\.cache*' ! -path '*.benchmarks*' ! -path '*docs*' ! -path '\./\.venv*' -print0 | sort -z | xargs -r0 cat | sha256sum | cut -f1 -d" " > prospector.sum
            fi

      - restore_cache:
          name: Restore Prospector
          keys:
            - v1-prospector-{{ .Branch }}-{{ checksum "prospector.sum" }}

      - run:
          name: Run prospector
          command: |
            . .venv/bin/activate
            set -x
            if [[ "${CIRCLE_BRANCH}" != "master" && "${CIRCLE_BRANCH}" != "stage" ]]; then
              if [ ! -e prospector.cache ]; then
                  prospector .
              fi
              touch prospector.cache
            fi

      - save_cache:
          name: Cache Prospector
          key: v1-prospector-{{ .Branch }}-{{ checksum "prospector.sum" }}
          paths:
            - ./prospector.cache

      - run:
          name: Run Pytests
          command: |
            . .venv/bin/activate
            pytest --cov-config .coveragerc --cov-report term-missing --durations=0 --cov . -vvv

  deploy-pypi:
    machine:
      enabled: true
    steps:
    - checkout
    - deploy:
        name: Deploy to PyPI
        command: |
          ./.circleci/deploy-to-pypi.sh

workflows:
  version: 2
  build_and_deploy:
    jobs:
      - build
      - hold:
          type: approval
          requires:
            - build
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/
      - deploy-pypi:
          requires:
            - build
            - hold
          filters:
            tags:
              only: /v[0-9]+(\.[0-9]+)*/
            branches:
              ignore: /.*/
